### ISSUE TITLE
Current errors with using safesearch and such.

### ISSUE THREAD

**Issue by JDJGInc** [miditkl/TenGiphPy#8]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Instead of safesearch in both make it the name that they use in the api themselves.
![image](https://user-images.githubusercontent.com/22802640/116754116-2ee83f00-a9d6-11eb-8bf6-d7bc9ea8119b.png)
^Screenshot of tenor's official api.

https://tenor.com/gifapi/documentation#quickstart-enhancedsearch
Look at the parameters. 

allow options for the language from: https://developers.giphy.com/docs/optional-settings/#language-support in giphy

![image](https://user-images.githubusercontent.com/22802640/116754298-7d95d900-a9d6-11eb-9869-e96704562792.png)
https://developers.giphy.com/docs/api/endpoint#search

**Comment by JDJGInc** [comment]
do get error of:

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/runner/JDBot/cogs/order.py", line 108, in tenor
    results = await self.client.loop.run_in_executor(None, tenor_client.search(args, safesearch=True, limit=10))
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: 'dict' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1353, in invoke
    await super().invoke(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
tho

**Comment by JDJGInc** [comment]
These should make it possible to add such features :D
